import type { Metadata } from "next";
import { PageHero } from "@/components/PageHero";
import { Reveal } from "@/components/Reveal";

export const metadata: Metadata = { title: "About", description: "Why GenuineGigs is building a governed operating layer for manufacturing work." };
export default function AboutPage() { return <>
  <PageHero eyebrow="Why GenuineGigs" title={<>Manufacturing deserves software that understands <em>how work really happens.</em></>} description="We are building the layer that connects operational responsibility, human judgment, enterprise systems, and capable agents." />
  <section className="section"><div className="shell split"><Reveal className="split-copy"><span className="eyebrow">Our point of view</span><h2>Transactions are only part of the story.</h2><p style={{color:"var(--slate)"}}>The real work of manufacturing lives between system entries: clarifying requirements, collecting evidence, chasing responses, comparing tradeoffs, routing decisions, coordinating teams, and resolving exceptions.</p></Reveal><Reveal><div className="content-card"><span className="tag">Visible operations</span><h3>Make that invisible work visible.</h3><p>GenuineGigs gives operational work an owner, a safe next action, the right context, and a reliable trail—then gives every role an agent that can help move it forward.</p></div></Reveal></div></section>
  <section className="mission dark-section"><div className="noise"/><Reveal className="mission-copy shell"><span className="eyebrow light">The mission</span><h2>More capable teams. More accountable operations.</h2><p>We believe industrial AI should make people better informed and better coordinated while keeping consequential authority clear.</p></Reveal></section>
  <section className="section"><div className="shell"><Reveal className="section-head center"><span className="eyebrow">How we build</span><h2>Grounded in work. Restrained by design.</h2></Reveal><div className="principle-grid" style={{borderColor:"var(--line)",background:"var(--line)"}}><article className="principle"><span>Practical</span><h3>Start with a complete lifecycle</h3><p>Procurement is the first end-to-end operating proof, from material need through quality inspection.</p></article><article className="principle"><span>Human</span><h3>Assist before automating authority</h3><p>Agents prepare the work and expose reasoning, evidence, missing context, and required decisions.</p></article><article className="principle"><span>Extensible</span><h3>Build for the whole plant</h3><p>The platform boundaries support future operations across stores, quality, production, maintenance, dispatch, finance, and management.</p></article></div></div></section>
</>; }
