import type { Metadata } from "next";
import { PageHero } from "@/components/PageHero";
import { Reveal } from "@/components/Reveal";

export const metadata: Metadata = { title: "About", description: "Why GenuineGigs is building a governed recovery operating system for manufacturing." };
export default function AboutPage() { return <>
  <PageHero eyebrow="Why GenuineGigs" title={<>Manufacturing deserves software built around <em>how recovery really happens.</em></>} description="We are building the operational layer between plant signals, human decisions, cross-functional work, and verified outcomes." />
  <section className="section"><div className="shell split"><Reveal className="split-copy"><span className="eyebrow">Our point of view</span><h2>The hard part starts after the alarm.</h2><p style={{color:"var(--slate)"}}>A machine condition, quality drift, material delay, or missed plan is only a signal. Teams still have to establish the facts, understand the loss, compare responses, coordinate ownership, and verify that production truly recovered.</p></Reveal><Reveal><div className="content-card"><span className="tag">Visible recovery</span><h3>Make that cross-functional work explicit.</h3><p>GenuineGigs gives every disruption a shared operational state, an explainable forecast, governed recovery options, accountable actions, and measurable evidence of the result.</p></div></Reveal></div></section>
  <section className="mission dark-section"><div className="noise"/><Reveal className="mission-copy shell"><span className="eyebrow light">The mission</span><h2>Faster recovery. More accountable operations.</h2><p>We believe industrial intelligence should help people make better decisions under pressure while keeping facts, authority, and outcomes clear.</p></Reveal></section>
  <section className="section"><div className="shell"><Reveal className="section-head center"><span className="eyebrow">How we build</span><h2>Grounded in facts. Governed in action.</h2></Reveal><div className="principle-grid" style={{borderColor:"var(--line)",background:"var(--line)"}}><article className="principle"><span>Operational</span><h3>Model the complete recovery loop</h3><p>From source event and deviation through decision, owned work, monitoring, verification, value, and learning.</p></article><article className="principle"><span>Human</span><h3>Make judgment easier to exercise</h3><p>Show assumptions, constraints, evidence, confidence, alternatives, and required authority where a decision is made.</p></article><article className="principle"><span>Honest</span><h3>Separate facts from interpretation</h3><p>Observed state, calculated impact, proposed recovery, and verified outcome remain distinct so the product never invents certainty.</p></article></div></div></section>
</>; }
