import type { Metadata } from "next";
import { ArrowRight, BadgeCheck, Database, Eye, FileCheck2, ShieldCheck, UserCheck } from "lucide-react";
import Link from "next/link";
import { CTASection } from "@/components/CTASection";
import { HomeMotion } from "@/components/HomeMotion";
import { ProductFrame } from "@/components/ProductFrame";

export const metadata: Metadata = { title:"Manufacturing Decision & Execution Platform", description:"See supply and production risk early, compare practical recovery plans, coordinate approved action, and verify the outcome with GenuineGigs.", alternates:{canonical:"/"} };
const loop=[
  ["Connect","Bring trusted planning and operational evidence together."], ["Anticipate","See expected and stress demand before uncertainty becomes disruption."], ["Detect","Identify material, supplier, and production exposure by date."], ["Decide","Compare feasible recovery plans and understand the trade-offs."], ["Act","Route approved work into procurement and operations."], ["Verify & Learn","Replan against fresh evidence and preserve what actually worked."]
];
const workflow=[
  ["Receipt moves","Updated supply is reconciled with current inventory, demand, and BOM requirements.","/product/supply-control-tower.png","Supply Chain Control Tower prioritizing critical material exposure"],
  ["Impact becomes visible","The future breach is dated and linked to affected products, work orders, and commitments.","/product/supply-horizon-current.png","Supply Horizon showing dated material coverage, receipts, and shortage windows"],
  ["Responses are compared","Expedite, transfer, alternate-source, allocation, and resequencing choices share one planning snapshot.","/product/material-plan-forecast.png","Material planning view comparing approved, expected, and stress demand"],
  ["Action is governed","An authorized person reviews the recommended recovery plan, its alternatives, evidence, and remaining constraints before structured work moves into execution.","/product/action-center-recovery-plans.png","Action Center comparing a recommended recovery plan with alternative plans, decision scores, evidence readiness, protection, exposure, and time to effect"],
];
const trust=[
  [Database,"System of record stays authoritative","GenuineGigs coordinates decisions above existing systems."], [UserCheck,"Human approval for consequential action","A recommendation is never permission to act."], [FileCheck2,"Evidence stays attached","Facts, assumptions, decisions, and outcomes remain traceable."], [Eye,"Unknown stays unknown","Missing or stale evidence remains a visible confirmation need."], [BadgeCheck,"Recovery must be observed","Completing a task is not proof that the operation recovered."]
];

export default function HomePage(){return <HomeMotion>
  <section className="hero"><div className="shell hero-grid"><div className="hero-copy"><p className="kicker">Manufacturing Decision & Execution Platform</p><h1>Turn factory disruption into a verified recovery plan.</h1><p>GenuineGigs connects demand, materials, suppliers, purchasing, and production so manufacturers can detect risk early, compare practical responses, govern action, and verify recovery.</p><div className="hero-actions"><Link className="primary-link" href="/demo">Book a factory workflow demo <ArrowRight size={17}/></Link><Link className="secondary-link" href="#recovery-workflow">See how recovery works</Link></div></div><div className="hero-proof"><ProductFrame priority src="/product/supply-horizon-current.png" width={1917} height={881} label="Supply Horizon · Active planning view" alt="GenuineGigs Supply Horizon showing material coverage, receipts, shortage windows, and intervention points"/><div className="hero-decision-card"><span>Recovery decision</span><strong>Interplant transfer + resequence</strong><div className="status-row"><span>Evidence ready</span><b>Recommended</b></div></div></div></div></section>
  <div className="proof-strip"><div className="proof-track">{[...Array(2)].flatMap((_,n)=>["Risk by date","Downstream impact","Feasible response","Human approval","Governed execution","Observed recovery"].map(x=><span key={`${n}-${x}`}>{x}<i/></span>))}</div></div>

  <section className="chapter problem"><div className="shell"><div className="chapter-head"><h2>Your factory does not need another dashboard. It needs a coordinated response.</h2><p>Shortages, supplier delays, demand changes, quality holds, and production constraints cross functions. Their evidence is spread across systems while the response is rebuilt through spreadsheets, calls, and follow-ups.</p></div><div className="comparison"><div className="compare-side"><p className="kicker">Today</p><h3>Signals appear. Coordination starts again.</h3><div className="flow-line">{["ERP + Excel","Manual reconciliation","Alert","Calls and messages","Disconnected action","Uncertain outcome"].map(x=><span key={x}>{x}</span>)}</div></div><div className="compare-side"><p className="kicker">With GenuineGigs</p><h3>One path from evidence to outcome.</h3><div className="flow-line">{["Trusted context","Risk + impact","Recovery choices","Approval","Execution","Verified outcome"].map(x=><span key={x}>{x}</span>)}</div></div></div></div></section>

  <section className="chapter"><div className="shell"><div className="chapter-head"><h2>One operating loop from signal to verified recovery.</h2><p>Visibility is only the beginning. GenuineGigs keeps the planning view, operational impact, decision, work, and fresh evidence connected until recovery holds.</p></div><div className="loop-grid">{loop.map(([title,copy],i)=><article className="loop-card" key={title}><span>{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>

  <section id="recovery-workflow" className="chapter workflow"><div className="shell workflow-grid"><div className="workflow-copy"><p className="kicker">Supplier-delay workflow</p><h2>A supplier delay is not just a supplier problem.</h2><p>Follow one changed receipt across planning, exposure, decision, approval, execution, and stable recovery.</p></div><div className="workflow-steps">{workflow.map(([title,copy,image,alt],i)=><article className="workflow-step" key={title}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{title}</h3><p>{copy}</p><div className="scroll-image"><ProductFrame src={image} width={1917} height={877} label={title} alt={alt}/></div></div></article>)}</div></div></section>

  <section className="chapter"><div className="shell predict-grid"><div className="predict-copy"><p className="kicker">Planning truth + predictive intelligence</p><h2>Make uncertainty operational.</h2><p>Expected demand helps teams plan. Stress demand helps them test resilience. Neither silently becomes operational truth. Authorized planners review scenarios, understand material consequences, and publish the approved planning view.</p><div className="evidence-list"><span>Expected range stays visible</span><span>Stress case shows material consequences</span><span>Approved plan remains authoritative</span></div><Link className="text-arrow" href="/platform/predictive-intelligence">Explore predictive intelligence <ArrowRight size={15}/></Link></div><div className="scroll-image"><ProductFrame src="/product/predictive-intelligence.png" width={1917} height={877} label="Predictive Intelligence · Active outlook" alt="Predictive Intelligence view with demand probability range and model-health evidence"/></div></div></section>

  <section className="chapter recovery"><div className="shell"><div className="chapter-head"><h2>From shortage alert to executable choices.</h2><p>Compare materially different responses against the same planning snapshot. See protection, remaining exposure, time to effect, constraints, and evidence readiness before action.</p></div><div className="plan-grid"><article className="plan-card"><span>Plan A</span><h3>Expedite + split receipt</h3><p>Protect the earliest work order while the balance follows on the confirmed lane.</p><div className="plan-metrics"><div><small>Protection</small><strong>Near-term build</strong></div><div><small>Constraint</small><strong>Premium freight</strong></div></div></article><article className="plan-card recommended"><span>Recommended plan</span><h3>Transfer + resequence</h3><p>Move usable stock from a sister plant and protect the highest-priority commitment first.</p><div className="plan-metrics"><div><small>Time to effect</small><strong>2 working days</strong></div><div><small>Evidence</small><strong>Ready to review</strong></div></div><div className="recommendation"><strong>Why this plan:</strong> earlier protection with known inventory and no supplier-qualification dependency.</div></article><article className="plan-card"><span>Plan C</span><h3>Alternate source + allocation</h3><p>Qualify a secondary source while available stock is allocated to critical demand.</p><div className="plan-metrics"><div><small>Remaining risk</small><strong>Qualification lead</strong></div><div><small>Side effect</small><strong>Lower-priority delay</strong></div></div></article></div></div></section>

  <section className="chapter"><div className="shell"><div className="chapter-head"><h2>Built around the decisions manufacturing teams actually make.</h2><p>See and understand risk, decide on a practical response, then act and verify—without turning the product into a catalogue of disconnected modules.</p></div><div className="experience-grid"><article className="experience-card"><p className="kicker">See & understand</p><h3>Supply Chain Control Tower and Supply Horizon</h3><p>Prioritize exposure and read coverage, receipts, shortage windows, and intervention dates on one planning view.</p><ProductFrame src="/product/supply-control-tower.png" width={1917} height={872} label="Control Tower" alt="Supply Chain Control Tower prioritizing critical risks and showing stale source evidence"/><Link href="/platform/supply-chain">Explore supply chain planning</Link></article><article className="experience-card"><p className="kicker">Decide</p><h3>Predictive Intelligence, Scenario Lab, and Recovery Workbench</h3><p>Test uncertainty and compare practical responses before changing the plan.</p><Link href="/platform/recovery-intelligence">Explore recovery intelligence</Link></article><article className="experience-card"><p className="kicker">Act & verify</p><h3>Action Center, Procurement, and Operations</h3><p>Route approved work to the teams that execute it, then replan from fresh evidence.</p><Link href="/platform/procurement">See governed execution</Link></article></div></div></section>

  <section className="chapter gigi"><div className="shell gigi-grid"><div className="gigi-copy"><p className="kicker">Gigi Manufacturing Companion</p><h2>Already watching. Ready when your team needs context.</h2><p>Gigi monitors operational change, brings attention to cases that need review, prepares briefings, follows commitments, and answers questions inside the active manufacturing context. Evidence governance and human authority remain visible throughout.</p><Link className="text-arrow" href="/gigi">Meet Gigi <ArrowRight size={15}/></Link></div><div className="scroll-image"><ProductFrame src="/product/gigi-contextual-answer.png" width={1917} height={880} label="Gigi · Evidence-governed case context" alt="Gigi answering what can be done for material MAT-0127 while the underlying recovery-plan comparison remains visible"/></div></div></section>

  <section className="chapter"><div className="shell"><div className="chapter-head"><h2>Add intelligence above the systems you already run.</h2><p>ERP remains authoritative. GenuineGigs brings evidence from planning and factory systems into connected decision and execution workflows, then expands authority only after the data and process are trusted.</p></div><div className="flow-line">{["Files / Excel","Read-only connections","Shadow operation","Governed writes"].map(x=><span key={x}>{x}</span>)}</div><p style={{marginTop:30}}><Link className="text-arrow" href="/integrations">See the adoption path <ArrowRight size={15}/></Link></p></div></section>

  <section className="chapter" style={{background:"#eef1ed"}}><div className="shell"><div className="chapter-head"><h2>Governed intelligence for real factory decisions.</h2><p>Control stays visible at every step—from source freshness and permissions to approval, external execution, and recovery evidence.</p></div><div className="trust-grid">{trust.map(([Icon,title,copy])=><article className="trust-card" key={title as string}><Icon/><h3>{title as string}</h3><p>{copy as string}</p></article>)}</div><p style={{marginTop:34}}><Link className="text-arrow" href="/security-governance">Explore security and governance <ArrowRight size={15}/></Link></p></div></section>

  <section className="chapter"><div className="shell"><div className="chapter-head"><h2>Start with one workflow, not a transformation program.</h2><p>A focused pilot lets teams validate evidence, decisions, and responsibility before widening system authority.</p></div><div className="pilot-path">{[["Bring the problem","Choose one recurring planning or recovery workflow."],["Map the evidence","Identify the source data and gaps that matter."],["Run in shadow","Compare outputs without changing authoritative systems."],["Validate together","Review decisions with the people who own them."],["Expand carefully","Enable controlled writes only after trust is earned."]].map(([t,c])=><article className="pilot-step" key={t}><h3>{t}</h3><p>{c}</p></article>)}</div></div></section>
  <CTASection/>
</HomeMotion>}
