import { Activity, ArrowRight, BadgeCheck, BrainCircuit, DatabaseZap, GitBranch, Network, Scale, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { HomeMotion } from "@/components/HomeMotion";
import { ProductFrame } from "@/components/ProductFrame";

const modules = [
  { key:"procurement", name:"Procurement", line:"From requirement to verified receipt.", copy:"Orchestrate RFQs, quotation intelligence, supplier decisions, approvals, purchase orders and inbound outcomes.", href:"/modules/procurement", image:"/product/modules/procurement.png", width:1600, height:905 },
  { key:"scm", name:"SCM", line:"See the next 210 days before they break.", copy:"Visualize coverage, receipts, shortage windows, production exposure, scenarios and intervention deadlines.", href:"/modules/scm", image:"/product/modules/scm-horizon.png", width:1920, height:1080 },
  { key:"operations", name:"Operations", line:"Turn disruption into verified recovery.", copy:"Connect live line state, production forecasts, cross-functional recovery and observed operational outcomes.", href:"/modules/operations", image:"/product/modules/operations-recovery.png", width:1920, height:900 },
];

const autonomy = ["Observe","Understand","Predict","Plan","Decide","Act","Verify","Learn"];

export default function HomePage(){return <HomeMotion>
  <section className="platform-hero"><div className="hero-field" aria-hidden="true"/><div className="shell platform-hero-grid"><div className="platform-hero-copy"><p className="platform-kicker">Intelligence for modern manufacturing</p><h1> All you need for your entire factory.</h1><p>GenuineGigs brings procurement, supply planning and factory operations together—so your teams spot disruption sooner, respond with confidence and keep production moving.</p><div className="hero-actions"><Link href="/demo" className="primary-link">See GenuineGigs in action <ArrowRight size={17}/></Link><Link href="/product" className="secondary-link">Explore the platform</Link></div><div className="hero-assurance"><span>Source-grounded</span><span>Human-governed</span><span>Outcome-verified</span></div></div><div className="platform-hero-visual image-motion"><div className="product-instrument-label"><span>LIVE PLANNING ENVIRONMENT</span><b>SCM / 210D</b></div><ProductFrame src="/product/modules/scm-horizon.png" width={1920} height={1080} alt="GenuineGigs SCM Supply Horizon visualizing material coverage and intervention points across 210 days" priority label="GenuineGigs SCM · Supply Horizon"/><div className="hero-product-index"><span>01 Procurement</span><span className="active">02 SCM</span><span>03 Operations</span></div></div></div></section>

  <section className="platform-marquee" aria-label="Manufacturing platform capabilities"><div>{[...Array(2)].flatMap((_,n)=>["Canonical manufacturing model","Event backbone","Relationship graph","Factory state","Planning intelligence","Governed actions","Verified outcomes"].map(item=><span key={`${n}-${item}`}>{item}<i/></span>))}</div></section>

  <section className="platform-core"><div className="shell"><div className="core-intro"><p className="section-coordinate">PLATFORM / SHARED CORE</p><h2>One source of operational truth. One system for action.</h2><p>Every module works from shared identities, source provenance, time-aware state, cross-module relationships, policy and action infrastructure.</p></div><div className="core-bento">
    <article className="core-brain"><div><BrainCircuit/><h3>The Factory Brain</h3><p>A canonical model and relationship graph connect suppliers, materials, products, BOMs, work orders, lines, equipment, inventory and purchase orders.</p></div><div className="brain-capabilities"><span>Canonical identity</span><span>Live factory state</span><span>Relationship intelligence</span><span>Source provenance</span></div></article>
    <article className="core-data"><DatabaseZap/><h3>One data and event backbone</h3><p>ERP, MES, Excel, email and plant signals retain source identity, provenance and correlation.</p></article>
    <article className="core-action"><ShieldCheck/><h3>Governed from recommendation to outcome</h3><p>Policy, approval, execution receipts and verification keep consequential action accountable.</p></article>
  </div></div></section>

  <section className="module-story"><div className="shell module-story-grid"><div className="module-story-intro"><p className="section-coordinate">PRODUCT / SYSTEMS OF WORK</p><h2>Three modules. Each complete in its own work.</h2><p>Start where the operational pain is highest. Expand without rebuilding the underlying truth.</p><div className="autonomy-line">{autonomy.map((item,index)=><span key={item} className={index<2?"lit":""}>{item}</span>)}</div></div><div className="module-story-list">{modules.map((module,index)=><article className={`story-module story-${module.key} image-motion`} key={module.name}><header><span>MODULE / 0{index+1}</span><h3>{module.name}</h3><Link href={module.href}>Open module <ArrowRight size={15}/></Link></header><div><div><strong>{module.line}</strong><p>{module.copy}</p></div><ProductFrame src={module.image} width={module.width} height={module.height} alt={`${module.name} product workspace`} label={`GenuineGigs ${module.name}`}/></div></article>)}</div></div></section>

  <section className="decision-section"><div className="shell"><p className="section-coordinate">CONTROL / DECISION PATH</p><div className="decision-copy"><h2>Move from visibility to a decision the business can trust.</h2><p>GenuineGigs keeps observed facts, derived intelligence, recommendations, authority, external execution and verified outcomes connected—but deliberately distinct.</p></div><div className="decision-ledger"><article><Activity/><span>Observe</span><strong>What is true now?</strong></article><article><Network/><span>Understand</span><strong>What depends on it?</strong></article><article><GitBranch/><span>Plan</span><strong>What changes the outcome?</strong></article><article><Scale/><span>Decide</span><strong>Who has authority?</strong></article><article><BadgeCheck/><span>Verify</span><strong>Did the operation recover?</strong></article></div></div></section>

  <section className="launch-section"><div className="shell"><div><h2>Start with one workflow. Build toward the manufacturing operating system.</h2><p>Bring an Excel planning sheet, a procurement process, or a recurring production disruption. We will map the first measurable deployment.</p></div><Link href="/demo" className="button button-light">Book a working session <ArrowRight size={17}/></Link></div></section>
</HomeMotion>}
