import type { Metadata } from "next";
import { DatabaseZap, FileClock, KeyRound, LockKeyhole, ShieldCheck, UserCheck } from "lucide-react";
import { PageHero } from "@/components/PageHero";
import { Reveal } from "@/components/Reveal";

export const metadata: Metadata = { title: "Enterprise", description: "Governed manufacturing recovery with plant-scoped access, deterministic operational logic, evidence, and controlled system integration." };
const principles = [
  { icon: UserCheck, title: "Authority follows the employee", copy: "Workspace membership, plant access, area, line, asset, role, approval scope, and financial visibility shape every response and action." },
  { icon: LockKeyhole, title: "Operational scope is enforced", copy: "The API filters plant objects and action paths—not merely the navigation—so a role cannot retrieve or mutate work outside its authority." },
  { icon: ShieldCheck, title: "Control lives outside the model", copy: "State transitions, forecasts, loss calculations, approvals, idempotency, and business rules remain deterministic and inspectable." },
  { icon: FileClock, title: "Evidence survives the incident", copy: "Source records, versions, decisions, acknowledgements, recovery measurements, and audit history remain durable after the shift changes." },
  { icon: KeyRound, title: "Source trust is visible", copy: "Freshness, delay, outage, replay, duplicate handling, and reconciliation are explicit so stale data cannot silently become operational truth." },
  { icon: DatabaseZap, title: "Integration boundaries are controlled", copy: "ERP, MES, WMS, QMS, CMMS, supplier, and edge data pass through authenticated connectors and canonical normalization before use." },
];

export default function EnterprisePage() { return <>
  <PageHero eyebrow="Enterprise by construction" title={<>Move recovery faster <em>without weakening control.</em></>} description="A governed architecture for plant-scale operational state, role-specific decisions, durable evidence, controlled actions, and reliable system boundaries." />
  <section className="section"><div className="shell"><Reveal className="section-head"><span className="eyebrow">Governance model</span><h2>Operational intelligence inside deterministic controls.</h2><p>Assistance can explain and investigate. The product still owns permissions, state, calculations, approvals, source integrity, and the authoritative workflow.</p></Reveal><div className="feature-grid">{principles.map((item,i)=><Reveal key={item.title} delay={(i%3)*80}><article className="feature-card"><span className="feature-icon"><item.icon /></span><h3>{item.title}</h3><p>{item.copy}</p></article></Reveal>)}</div></div></section>
  <section className="section dark-section"><div className="shell"><Reveal className="section-head"><span className="eyebrow light">Accountable adoption</span><h2>Validate with plant facts before widening authority.</h2></Reveal><div className="principle-grid"><article className="principle"><span>Isolation</span><h3>Tenant, plant, line, and asset boundaries</h3><p>Corporate comparison and plant execution can share a platform without sharing unauthorized operational or financial detail.</p></article><article className="principle"><span>Verification</span><h3>Observed evidence closes recovery</h3><p>Output, equipment condition, quality, material readiness, and sustained performance determine whether a recovery actually worked.</p></article><article className="principle"><span>Resilience</span><h3>Degraded sources stay visible</h3><p>Freshness and replay behavior are explicit, while the underlying operating workflow remains usable during integration or assistance outages.</p></article></div></div></section>
  <section className="section"><div className="shell split"><Reveal className="split-copy"><span className="eyebrow">Integration readiness</span><h2>Connect existing systems through one canonical boundary.</h2><p style={{color:"var(--slate)"}}>Production plans and actuals, downtime, inventory, supplier commitments, quality, machine events, and maintenance work are normalized before detectors, forecasts, recovery logic, or role views consume them. Customer mappings and write permissions are validated for each deployment.</p></Reveal><Reveal><div className="content-card"><span className="tag">Controlled rollout</span><h3>Simulate, shadow, verify, then enable</h3><p>Teams can validate mappings, event behavior, workflow, role scope, and reconciliation in an isolated operating model before authorizing live external effects.</p></div></Reveal></div></section>
</>; }
