import type { Metadata } from "next";
import { Activity, BadgeCheck, BookOpenCheck, Boxes, CircleGauge, Factory, ShieldCheck, Wrench } from "lucide-react";
import { PageHero } from "@/components/PageHero";
import { ProductFrame } from "@/components/ProductFrame";
import { Reveal } from "@/components/Reveal";

export const metadata: Metadata = { title: "Product", description: "Explore role-specific plant operations, deviation detection, bounded forecasts, recovery intelligence, governed actions, and verified outcomes in GenuineGigs." };
const cards = [
  { icon: Factory, tag: "Role workspaces", title: "The right operation for every role", copy: "Corporate, plant, production, maintenance, quality, purchase, stores, gate, and operators each receive a scoped view of the same operational truth." },
  { icon: Activity, tag: "Operational state", title: "Keep facts separate from interpretation", copy: "Execution, performance, quality, material, source freshness, and recovery state remain independently visible so one issue cannot hide another." },
  { icon: CircleGauge, tag: "Forecasting", title: "Know what the shift can still deliver", copy: "Bounded trajectories combine elapsed time, observed output, current line state, downtime, and approved recovery assumptions without unexplainable jumps." },
  { icon: Wrench, tag: "Recovery", title: "Compare realistic ways back", copy: "Recovery options expose expected output, constraints, owners, risks, prerequisites, and confidence before a person commits the plant." },
  { icon: Boxes, tag: "Readiness", title: "Connect material risk to production", copy: "Inventory, staging, inbound receipts, supplier commitments, inspections, and shortages show the operational consequence—not just stock rows." },
  { icon: ShieldCheck, tag: "Governance", title: "Route decisions through real authority", copy: "Plant, area, line, asset, role, financial visibility, and approval scope are enforced in the API as well as the interface." },
  { icon: BookOpenCheck, tag: "Knowledge", title: "Use only approved operational knowledge", copy: "Current SOPs, quality plans, manuals, and maintenance instructions are distinguished from superseded revisions and cited in context." },
  { icon: BadgeCheck, tag: "Verification", title: "Measure recovery from observed evidence", copy: "The system verifies output, condition, quality, readiness, and sustained stability before it records a recovered outcome or learned pattern." },
];

export default function ProductPage() { return <>
  <PageHero eyebrow="Manufacturing recovery, made operational" title={<>See the disruption. Choose the response. <em>Prove the recovery.</em></>} description="GenuineGigs creates a shared operational model from plant systems and live events, then turns deviations into governed, role-owned recovery work." />
  <section className="section"><div className="shell content-grid">
    <Reveal className="content-card wide role-home-card"><div><span className="tag">Role-specific home</span><h3>Start with what this person can understand, decide, and own.</h3><p>Each home experience is composed for the role—from plant trajectory and major losses to assigned line checks, maintenance work, quality holds, material risks, or integration health.</p></div><ProductFrame src="/product/plant-manager-home.png" width={1917} height={872} alt="Plant manager home showing operational trajectory, assigned work, exceptions, and decisions" /></Reveal>
    {cards.map((card, i) => <Reveal key={card.title} className="content-card" delay={(i % 2) * 90}><card.icon className="feature-icon" size={52} /><h3>{card.title}</h3><span className="tag">{card.tag}</span><p>{card.copy}</p></Reveal>)}
  </div></section>
  <section className="section dark-section"><div className="shell split"><Reveal className="split-copy"><span className="eyebrow light">Line recovery workspace</span><h2>Understand the loss before choosing the action.</h2><p>Production trajectory, operational dimensions, current recovery, loss attribution, constraints, and expected impact stay together—without pretending a machine event is already a diagnosed scenario.</p></Reveal><Reveal className="product-stack"><ProductFrame src="/product/line-recovery-workspace.png" width={1918} height={875} alt="Line recovery workspace with trajectory, operational dimensions, recovery status, and loss tree" label="Line recovery" /></Reveal></div></section>
  <section className="section"><div className="shell split reverse"><Reveal className="product-stack"><ProductFrame src="/product/material-readiness-gigi.png" width={1918} height={877} alt="Material readiness and inbound supply with contextual Gigi guidance" label="Material readiness" /></Reveal><Reveal className="split-copy"><span className="eyebrow">Context where the decision happens</span><h2>Ask better questions without leaving the operation.</h2><p>Gigi works with authorized plant context to explain risk, surface supporting evidence, and guide investigation. It does not replace deterministic operational state or human authority.</p></Reveal></div></section>
  <section className="section"><div className="shell split"><Reveal className="split-copy"><span className="eyebrow">Controlled knowledge</span><h2>Current instructions in. Superseded guidance out.</h2><p>Approved revisions are searchable and usable in operational context while withdrawn and superseded documents remain excluded from active guidance.</p></Reveal><Reveal className="product-stack"><ProductFrame src="/product/approved-knowledge.png" width={1918} height={876} alt="Approved manufacturing knowledge with current revisions and excluded superseded documents" label="Approved knowledge" /></Reveal></div></section>
</>; }
